# Generated by Django 5.2.12 on 2026-05-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('acao_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('valor_esperado', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
