# Generated by Django 5.2.14 on 2026-06-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='acao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to={'acoes_fotos/'}),
        ),
    ]
