# Generated by Django 5.2.14 on 2026-05-20 15:35

import doadores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.CharField(default=doadores.models.gerar_nanoid, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Não informado', max_length=100)),
                ('idade', models.IntegerField(default='Não informado')),
                ('email', models.EmailField(default='Não informado', max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
