# Generated by Django 5.2.14 on 2026-06-09 19:05

import doadores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.CharField(default=doadores.models.gerar_nanoid, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Não informado', max_length=100)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
