# Generated by Django 5.2.14 on 2026-05-20 19:54

import doadores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='id',
            field=models.CharField(default=doadores.models.gerar_nanoid, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
