# Generated by Django 5.2.14 on 2026-06-09 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acoes', '0001_initial'),
        ('doadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes_acao', to='acoes.acao')),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to='doadores.doador')),
            ],
        ),
    ]
